#! /bin/sh
set -e

## Wallpaper
change_desktop_background() {
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background \
	desktop-background \
	/usr/share/images/desktop-base/ezgo12-wallpaper-2560x1600.png 95
    update-alternatives --install \
        /usr/share/images/desktop-base/desktop-background.xml \
	desktop-background.xml \
	/usr/share/images/desktop-base/ezgo-wallpaper.xml 30

#    for WALLPAPER in ezgo12-wallpaper-1366x768.png \
#        ezgo12-wallpaper-2560x1600.png \
#		ezgo12-wallpaper-1920x1080.png ; do
#	update-alternatives --install \
#	        /usr/share/images/desktop-base/desktop-background \
#		desktop-background \
#		/usr/share/images/desktop-base/$WALLPAPER 60
#    done
}

restore_desktop_background() {
    update-alternatives --remove \
	desktop-background \
	/usr/share/images/desktop-base/ezgo12-wallpaper-2560x1600.png
    update-alternatives --remove \
	desktop-background.xml \
	/usr/share/images/desktop-base/ezgo-wallpaper.xml

#    for WALLPAPER in ezgo12-wallpaper-1366x768.png \
#        ezgo12-wallpaper-2560x1600.png \
#		ezgo12-wallpaper-1920x1080.png ; do
#	update-alternatives --remove desktop-background \
#		/usr/share/images/desktop-base/$WALLPAPER
#    done
}

install_default_dm_background() {
    update-alternatives --install \
        /usr/share/images/desktop-base/ezgo-default-dm.png \
        ezgo-default-dm.png \
        /usr/share/ezgo/ezgo-artwork/default-dm/ezgo12-dm-background-1920x1080.png 60
}

remove_default_dm_background() {
    update-alternatives --remove ezgo-default-dm.png \
        /usr/share/ezgo/ezgo-artwork/default-dm/ezgo12-dm-background-1920x1080.png
}

compile_gschemas() {
    glib-compile-schemas /usr/share/glib-2.0/schemas/
}

case "$1" in
  configure)
    change_desktop_background
    install_default_dm_background
    compile_gschemas
    ;;
  remove)
    restore_desktop_background
    remove_default_dm_background
    compile_gschemas
    ;;
esac
