#! /bin/sh
set -e

# Lightdm-kde-greeter
change_lightdm_lxde_theme() {
    if [ -d /etc/lightdm ]; then
		if [ -f /etc/lightdm/lightdm-gtk-greeter.conf ]; then
			cp -f /etc/lightdm/lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf.ezgo-bak
		fi
		sed -i 's/background=.\+$/background=\/etc\/alternatives\/ezgo-default-dm.png/g' /etc/lightdm/lightdm-gtk-greeter.conf
	fi
}

restore_lightdm_lxde_theme() {
    if [ -d /etc/lightdm ]; then
		if [ -f /etc/lightdm/lightdm-gtk-greeter.conf.ezgo-bak ]; then
			cp -f /etc/lightdm/lightdm-gtk-greeter.conf.ezgo-bak /etc/lightdm/lightdm-gtk-greeter.conf
			rm -f /etc/lightdm/lightdm-gtk-greeter.conf.ezgo-bak
		fi
	fi
}

change_ezgo_font_config() {
    if [ -f /usr/local/share/fonts/s/SourceHanSans-Normal.otf ]; then
	    sed -i 's/^\(font=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(menuFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(desktopFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(toolBarFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(smallestReadableFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(taskbarFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
	    sed -i 's/^\(activeFont=\)[^,]\+/\1Source Han Sans/g' /usr/share/ezgo/ezgo-kde/kde-profile/share/config/kdeglobals /etc/skel/.kde/share/config/kdeglobals
    fi
}

change_menu_prefix() {
	cp -f /etc/xdg/lxsession/Lubuntu/desktop.conf /usr/share/ezgo/ezgo-lxde/desktop.conf.ezgo-bak
	sed -i 's/menu_prefix=lxde-/menu_prefix=ezgo-/g' /etc/xdg/lxsession/Lubuntu/desktop.conf
}

restore_menu_prefix() {
	if [ -e /usr/share/ezgo/ezgo-lxde/desktop.conf.ezgo-bak ]; then
		mv -f /usr/share/ezgo/ezgo-lxde/desktop.conf.ezgo-bak /etc/xdg/lxsession/Lubuntu/desktop.conf
	fi
}

change_desktop_background() {
	cp -f /etc/xdg/pcmanfm/lubuntu/pcmanfm.conf /usr/share/ezgo/ezgo-lxde/pcmanfm.conf.ezgo-bak
	sed -i 's/wallpaper=.\+$/wallpaper=\/etc\/alternatives\/desktop-background/g' /etc/xdg/pcmanfm/lubuntu/pcmanfm.conf
}

restore_desktop_background() {
	if [ -e /usr/share/ezgo/ezgo-lxde/pcmanfm.conf.ezgo-bak ]; then
		mv -f /usr/share/ezgo/ezgo-lxde/pcmanfm.conf.ezgo-bak /etc/xdg/pcmanfm/lubuntu/pcmanfm.conf
	fi
}

case "$1" in
  configure)
    change_lightdm_lxde_theme
#    change_ksplash
#    change_ezgo_font_config
	change_menu_prefix
	change_desktop_background
    ;;
  remove)
    restore_lightdm_lxde_theme
#    restore_ksplash
	restore_menu_prefix
	restore_desktop_background
    ;;
esac
